services:
  mongodb:
    image: mongo
    container_name: Mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

  validacion:
    build: ./Validacion
    container_name: Validacion
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  generador:
    build: ./Generador
    container_name: Generador
    restart: always
    depends_on:
      - validacion
    environment:
      API_URL: http://validacion:8000/datos/
    command: ["python", "generador.py"]

  procesamiento:
    build: ./Procesamiento
    container_name: Procesamiento
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017
    command: ["python", "procesador.py"]

volumes:
  mongodb_data:
  grafana_data:
